### ISSUE TITLE
Problematic versions of numpy library in the MNIST example

### ISSUE THREAD

**Issue by ladi-pomsar** [SubstraFoundation/substra-examples#7]
Hi everyone,

today, while trying to run the MNIST example, I have managed to come into conflict of library versions. In the requirements.txt, numpy==1.19.1 is required alongside tensorflow 2.3.0. However, it seems that tensorflow 2.3.0 only supports numpy < 1.19. and >=1.16.  Changing numpy to 1.18.5 seems to work.

![obrázok](https://user-images.githubusercontent.com/67092607/135867120-9bcef101-2590-416b-8bcb-078181cba50c.png)

**Comment by RomainGoussault** [comment]
Hello,

Sorry for the late reply. This repo is not maintained anymore. We are going to archive it.

**Comment by RomainGoussault** [comment]
A new repo with examples will come up soon.
